wg-easy/wg-easy

- README.md
- docker-compose.yml
- src/config.js
- src/lib/WireGuard.js
Add missing var for allowed IPs. 
https://github.com/WeeJeWel/wg-easy/issues/19
I am not a coder nor did I ever touch any java code. Please correct possible syntax errors and merge.
Thanks!
> add WG_ALLOWED_IPS

- README.md
- src/config.js
- src/lib/Server.js
- src/lib/WireGuard.js
> Adding PersistentKeepalive

- src/www/index.html
Fixes #251.
This PR is separated from #178.
> Fix modals flashing on reload

- README.md
- docker-compose.yml
- src/config.js
- src/lib/WireGuard.js
Exposed PreUp and PreDown as environment variables.
PR for issue #176.
> Add PreUp and PreDown

- src/www/index.html
As discussed earlier with @WeeJeWel and @pheiduck, this change:
1. Adds automatic dark mode based on underlying system
2. Removes the manual toggle.
> Add auto dark mode and remove toggle

- Dockerfile
fixes: https://github.com/wg-easy/wg-easy/issues/682
> Fix: iptables cannot be executed correctly on certain environments

- src/config.js
> config.js: revert fixed MTU 1420

- .github/workflows/deploy-development.yml
- Dockerfile
- docs/changelog.json
- src/package.json
Version 9 release, which fixes https://github.com/wg-easy/wg-easy/issues/682, through the use of `iptables-legacy`.
> Version 9: Fix issue running on older kernels

- src/package-lock.json
- src/package.json
as its needed for `eslint-config-athom`: see: https://github.com/athombv/eslint-config-athom?tab=readme-ov-file#usage
> revert: install eslint as dev-package

- README.md
- docker-compose.yml
- src/config.js
- src/lib/WireGuard.js
> revert: custom interface

- README.md
> Add guidance where no DNS is desired

- .github/workflows/deploy-nightly.yml
Remove unused: `Set environment variables` Step on deploy-nightly CI
> deploy-nightly.yml: Release number is not provieded

- .github/workflows/stale.yml
https://github.com/actions/stale/releases/tag/v9
> stale.yml: update to v9

- .github/workflows/stale.yml
[Best practices for using the REST API](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28)
> stale.yml: do 5 operation per run

- contributing.md
The `contributing.md` is autogenerated 
Needs Review from @WeeJeWel and @peterlewis
> Add Contributing Guidelines

- LICENSE.md
- src/www/index.html
LICENSE based on CC BY-NC-SA 4.0
https://creativecommons.org/licenses/by-nc-sa/4.0/
> LICENSE based on CC BY-NC-SA 4.0

- .github/workflows/npm-update-bot.yml
- src/package.json
- src/www/css/app.css
in the future npm-update-bot will handle it for us.
> update: app.css to match latest tailwindcss version

- src/www/index.html
tested it is now build local and not from the cdn playground
> index.html: use app.css

- src/www/index.html
Just to have the logo presented on the Login Page as well.
> index.html: logo on loginpage

- src/lib/WireGuard.js
> Remove redundant newline char in generated client configuration

- src/tailwind.config.js
- src/www/css/app.css
- src/www/index.html
- Changed layout so controls are wrapped first. Info block and RX/TX stay in line until 450px width
- Fix last seen showing `54 years` on new clients
> Fix detailed stats

- docs/changelog.json
- src/www/css/app.css
- src/www/js/app.js
- Fixed error in changelog.json
- Updated css
- Some refactoring on fetching uiDetailedStats
Hope everything's ok this time :)
> Fix detailed stats 2

- docs/changelog.json
- src/package-lock.json
Security Patch:
https://github.com/advisories/GHSA-78xj-cgh5-2h22
> Workaround CVE-2023-42282

- src/config.js
- src/lib/WireGuard.js
- src/server.js
> feat: support graceful shutdown

- src/www/css/app.css
- src/www/index.html
Minor changes to fix text wrapping on small screens & #762
> Fix simple stats wrapping on mobile

- src/lib/WireGuard.js
Import json configurations with no PreShared-Key (#341) from @t-oster
new Branch for testing and merge into `master`
> Import json configurations with no PreShared-Key

- .github/workflows/deploy.yml
> deploy.yml: rebuild v11

- .github/workflows/deploy.yml
> Revert "deploy.yml: rebuild v11"

- docs/changelog.json
- src/package.json
> Revert "[update] package.json and changelog to current release 12"

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-pr.yml
A better solution we have until now as push to our repo is not working (from external prs) so only build the image to test if it work or not.
> PR: Build Docker images

- README.md
`README.md` was updated to provide installation and update instructions for Docker Compose as well.
This merge request is in response to #900.
> Add setup and update instructions for Compose

- src/lib/Server.js
> fix: add Content-Type header for static files

- src/config.js
> fix backward compatibility issue in #888 

- src/config.js
> Fix WG_DEFAULT_ADDRESS if not set

- Dockerfile
- docker-compose.yml
> healthcheck is integrated internally 

- .dockerignore
- Dockerfile
- package.json
- src/package-lock.json
- src/package.json
- src/server.js
> Improved local development and Dockerfile

- src/lib/Server.js
Some users can no longer access the Web UI since the release of v13.
Fixes: #1035
> fixup: Server.js for instance without docker

- README.md
- src/config.js
> fixup: WG_PORT in config.js

- README.md
Just a Documentation of the docker image versions we provied to help users to understand the "version tree".
Closes: #1066
> Documentation: image tags and UI_CHART_TYPE

- docker-compose.yml
First off, great piece of software! But as a Podman user, it took me longer than I'd like to figure out what was going wrong.
There is only one mention of Podman on the issue tracker, and the "solution" is a broken link. It is mentioned on the wiki, however; but I feel most won't check there, or at least, not at first.
> Inform Podman users about cap-add=NET_RAW

- Dockerfile
- README.md
- docker-compose.yml
- src/config.js
- src/lib/Server.js
- src/lib/Util.js
- src/lib/WireGuard.js
- src/www/index.html
- src/www/js/api.js
- src/www/js/app.js
IPv6 Support thanks to @crazyracer98, @pheiduck, @peterlewis 
Close: #138 
Close: #781 
Original PR: #781 
As I didnt want to deal with merge conflicts, I manually reapplied the code and updated it. I included the contributers to the original pr as co-authors
> IPv6 support

- Generate.bcrypt.hash.md
Thanks to: @mathys-lopinto
Additionally, we could add an installation guide for Fedora and Arch Linux.
Fixes #1127
Closes #1131
> Add: Generate.bcrypt.hash.md

- How_to_generate_an_bcrypt_hash.md
- README.md
- docker-compose.yml
- Rename the file to a more readable name
- Add one-liner command for quick execution
- Include dedicated paragraph on using the output
- Implement assert to prevent bcrypt limitation issues
- Comment the python script
- Improves clarity and usability of bcrypt documentation
- Mention documentation file in docker-compose.yml and README.me file
> Enhance bcrypt doc: rename, add one-liner, usage info, and assert

- src/lib/Server.js
- src/www/css/app.css
- src/www/index.html
Fix the icons & buttons view in #1166 
* update the viewBox of svg elements
* add cursor pointer when hover the restore button
* rebuild the css
> fix: icons & buttons view

- src/config.js
- src/lib/WireGuard.js
- src/www/js/api.js
- src/www/js/app.js
> update ipv6 support v2

- How_to_generate_an_bcrypt_hash.md
Correcting spelling in How_to_generate_an_bcrypt_hash.md
> Spelling in How_to_generate_an_bcrypt_hash.md

- docker-compose.dev.yml
Improving compose file for dev.
Some variables are missing which lead to an error. 
Fixes: #1234
> fixup: docker-compose.dev.yml

- src/lib/Server.js
- src/www/index.html
- src/www/js/app.js
Bug fixes for new features
The client sorting functionality is broken. This is a fix for UI_ENABLE_SORT_CLIENTS and another fix for UI_TRAFFIC_STATS
I tested this on my computer by running the code
> Fix sort clients

- src/www/js/i18n.js
> Russian translation

- .editorconfig
- README.md
- docker-compose.yml
- src/config.js
- src/lib/Server.js
- src/lib/WireGuard.js
- src/package-lock.json
- src/package.json
- src/www/css/app.css
- src/www/index.html
- src/www/js/api.js
- src/www/js/app.js
- src/www/js/i18n.js
- src/www/src/css/app.css
New feature, allows you to specify the VPN validity period for the client
When environment WG_ENABLE_EXPIRES_TIME is enabled, the certificate expiration date is displayed in the web interface. Once a minute a check for an expired certificate is performed and the client with an expired certificate is disabled. 
https://github.com/wg-easy/wg-easy/issues/1287
Tested this on my computer
> Feat expiration date

- src/lib/Server.js
- src/lib/WireGuard.js
- src/www/index.html
- src/www/js/api.js
- src/www/js/app.js
- src/www/js/i18n.js
This update creates a button to generate a one-time short link. The link is no longer valid after it has been used once. This will fix a security issue
There are changes to the interface.
https://github.com/wg-easy/wg-easy/pull/1288  security issue
On me server
> Fix short link. Generate One Time Link

- README.md
- docker-compose.yml
- src/config.js
- src/lib/Server.js
- src/lib/WireGuard.js
- src/www/index.html
- src/www/js/api.js
- src/www/js/app.js
rename from `ui_show_links` to `wg_enable_one_time_clicks`
disallow generating if feature is disabled (should also be done for client expiry
expire otl after 5 minutes
Closes #1302 
Run locally, tested if expiry works
No ui changes
> Fix One Time Links

- How_to_generate_an_bcrypt_hash.md
> Fix typo in How_to_generate_an_bcrypt_hash.md

- docker-compose.dev.yml
- src/config.js
- src/lib/Server.js
Fail if old Password Var is still used
Closes #1269
See #1269
This does not exit explicitly, but as its an unhandled error it crashes the server
Tested locally
N/A
> Fail if old Password Var is still used

- src/server/utils/WireGuard.ts
- src/services/database/lowdb.ts
- src/services/database/repositories/client.ts
- src/services/database/repositories/database.ts
- src/services/database/repositories/user.ts
The Database Date Type is string, as Date to JSON automatically (transparent to the developer) converts to ISO string.
But if the value is then read again its still a string instead of a Date (which typescript thinks otherwise)
Types are inconsistent. Type coercion
TODO
N/A
> Fix: Database Date type

- src/server/utils/WireGuard.ts
- src/server/utils/config.ts
- src/server/utils/ip.ts
Add Function to migrate from old to new database
Not everything will work as is, but old clients should still work
TODO
N/A
> Feat: Migration

- CHANGELOG.md
- package.json
- src/app/layouts/Header.vue
- src/app/stores/global.ts
- src/package.json
- src/pnpm-lock.yaml
- src/server/api/release.get.ts
- src/server/utils/config.ts
- src/server/utils/release.ts
Closes #1293 
This adds a Changelog and support for Release Notes
Improve Update experience
Locally
N/A
> Feat: Changelog, Release Notes

- src/app/app.vue
- src/app/layouts/Footer.vue
- src/app/layouts/Header.vue
- src/app/stores/global.ts
- src/server/api/release.get.ts
- src/server/utils/config.ts
- src/server/utils/release.ts
This improves GitHub Release Logic
This shows current version in ui footer
Closes #1388 
Old:
WireGuard Easy © 2021-2024 by Emile Nijssen is licensed under CC BY-NC-SA 4.0 · Donate
New:
WireGuard Easy (v14.0.0) © 2021-2024 by Emile Nijssen is licensed under CC BY-NC-SA 4.0 · Donate
> Feat: Show Version in Footer

- README.md
Version bump to 14 inside the Readme file.
> Update README.md - Version Bump to 14

- README.md
The following minor improvements were made to `README.md`:
- The notice about stable version was styled as block quote to emphasize it more and it was moved right after the title of the section "Versions", and a link to the production branch was added;
- versions table was updated to add links to branches for easier navigation;
- some typos were fixed;
- wording was changed in couple of places to make it simpler;
- the `docker run` command was updated to:
- use long options to make it more self-explanatory;
- wrap password hash value placeholder in single quotes to avoid variable expanding as password hashes tend to contain `$`;
- some other very minor changes to make `docker run` options uniform.
I saw the opportunity to improve the documentation by:
- emphasizing important information; …
> Make minor improvements for `ReadMe.md`

- README.md
- src/app/components/Form/ArrayField.vue
- src/app/components/Ui/Footer.vue
- src/app/pages/index.vue
- src/i18n/locales/en.json
- src/server/api/session.post.ts
- src/server/api/setup/2.post.ts
- src/server/api/setup/4.post.ts
- src/server/api/setup/migrate.post.ts
- src/server/database/repositories/client/service.ts
- src/server/database/repositories/general/types.ts
- src/server/database/repositories/oneTimeLink/service.ts
- src/server/database/repositories/oneTimeLink/types.ts
- src/server/database/repositories/user/service.ts
- src/server/database/repositories/user/types.ts
- src/server/database/schema.ts
- src/server/middleware/setup.ts
- src/server/utils/WireGuard.ts
- src/server/utils/handler.ts
- src/server/utils/session.ts
- src/server/utils/types.ts
This implements stuff written in TODO comments
> Chore: TODOs

- docs/content/advanced/migrate/from-14-to-15.md
- docs/content/index.md
- docs/mkdocs.yml
- src/server/api/setup/migrate.post.ts
This adds to some more information to the docs, and fixes the license and copyright issues
it also fixes migration for older wg-easy versions
> Fix: Various

- src/i18n/locales/en.json
- src/server/database/repositories/interface/service.ts
- src/server/database/repositories/interface/types.ts
Only recalculate IP address if the Cidr changed
Fixes #1707
> Fix: Cidr Change

- src/app/pages/me.vue
- src/app/pages/setup/2.vue
- src/i18n/locales/en.json
- src/server/database/repositories/user/types.ts
The user has to confirm the password in the setup process to avoid misspells
Closes #1721
> Feat: Confirm setup password

- package.json
- src/package.json
- src/pnpm-lock.yaml
- src/server/database/repositories/client/service.ts
If you update the IP for a client, the Address cold be outside of the cidr range.
This also updates some packages
> Fix: Update ip outside of cidr

- src/app/components/Admin/SuggestDialog.vue
- src/app/components/Form/HostField.vue
- src/app/pages/admin/config.vue
- src/i18n/locales/en.json
This PR fixes the long loading if DNS server is not reachable, even when not opening the dialog.
now it only shows a loading text for a long time but navigation is instant
> Fix: slow suggest Host Address

- src/i18n/locales/en.json
- src/server/database/repositories/user/types.ts
This pull request includes changes to the `src/server/database/repositories/user/types.ts` file to adjust the validation rules for usernames and passwords. The most important changes include modifying the minimum length requirement for usernames and updating the regular expression for password special characters.
This change fixes #1744, any discussion and suggestions are welcome.
> Improvements to username and password validations (#1744)

- src/i18n/locales/en.json
- src/package.json
- src/pnpm-lock.yaml
- src/server/database/repositories/general/service.ts
- src/server/database/repositories/general/types.ts
- src/server/utils/password.ts
This hashes the metrics password if it is not already hashed
this allows the user to either supply a plain text password or a argon2 hash
> Feat: Hash metrics password

- src/app/components/Header/Insecure.vue
- src/app/components/Header/Update.vue
- src/app/components/Ui/Footer.vue
- src/app/pages/login.vue
- src/app/stores/global.ts
- src/i18n/locales/en.json
- src/server/api/information.get.ts
Shows a warning if insecure is false and the connection is not over http.
Breaking: moves /api/release to /api/information
> Feat: Show insecure warning

- src/server/plugins/manager.ts
This PR adds information to the container logs on startup
> Feat: startup info

- src/server/database/migrations/0000_short_skin.sql
- src/server/database/migrations/meta/0000_snapshot.json
- src/server/database/migrations/meta/0001_snapshot.json
- src/server/database/migrations/meta/_journal.json
- src/server/database/repositories/client/schema.ts
- src/server/database/repositories/client/types.ts
- src/server/utils/WireGuard.ts
- src/server/utils/wgHelper.ts
This PR adds the Endpoint field to the `wg0.conf` to the server
This has no UI and will not have it until requested
> Feat: Server Endpoint

- .github/workflows/deploy-edge.yml
- CHANGELOG.md
- docs/content/contributing/general.md
- docs/content/contributing/issues-and-pull-requests.md
- docs/content/getting-started.md
This pr replaced the `nightly` workflow and tag with `edge`
there will be no sudden change when using `nightly`
the docs will be built on every push
> replace nightly with edge

- docker-compose.beta.yml
- docker-compose.yml
> publish stable docker compose

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-edge.yml
- .github/workflows/deploy-pr.yml
- .github/workflows/deploy.yml
- Dockerfile
This PR distributes the docker build process across different runners. as the runners can now be the same arch as the target image and will run in parallel, the builds are way faster
> Feat: distributed build

- src/i18n/i18n.config.ts
- src/i18n/locales/zh-HK.json
- src/nuxt.config.ts
This PR introduces Traditional Chinese (Hong Kong) localization, identified by the `zh-HK` locale code. It provides a fully localized experience for users in Hong Kong and Taiwan.
I like the app, want to make it more accessible.
> feat: Add Traditional Chinese (zh-HK) i18n Support

- src/i18n/i18n.config.ts
- src/i18n/locales/pt-BR.json
- src/nuxt.config.ts
Add i18n Português Brasil translation.
Simply want to contribute to another language translation.
This is not tested in my local yet.
> feat: Add Português Brasil translation

- src/i18n/locales/fr.json
> French language update

- Dockerfile
- src/nuxt.config.ts
- src/server/utils/config.ts
- src/server/utils/wgHelper.ts
This PR implements: installing amneziawg-tools and defining the wireguard-tools executable. 
If the user has the amneziawg kernel module, it will be used instead of the regular wg.
This PR does not add anything to the UI or DB.
partially solves #2053
> feat: add amneziawg support

- .github/workflows/deploy-development.yml
- .github/workflows/deploy-edge.yml
- .github/workflows/deploy.yml
Publishes the wg-easy container to codeberg
closes #2152 
see #2152 
see https://docs.docker.com/build/ci/github-actions/copy-image-registries/
> Feat: Publish package on Codeberg
