wg-easy/wg-easy

- Dockerfile
* Added `--no-cache` to avoid caching apk downloads
* Added `dumb-init` package to avoid zombie processes since node is not suppose to run as PID 1.
More information here: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/
> Add dumb-init to avoid zombie processes.

- README.md
Added a sentence to explain the keepalive variable better to new users of WireGuard.
This hopefully prevents misunderstandings like #264
> docs: :memo: added keepalive explanation

- README.md
- src/config.js
Fix hardcoding of `eth0` device name.
> add wireguard device parameter

- README.md
- src/config.js
- src/lib/WireGuard.js
Revert port *inside* container to 51820. Fixes https://github.com/wg-easy/wg-easy/issues/692.
> Revert port variable-isation *inside* container

- src/lib/WireGuard.js
Hi. When migrating old setups, one may want to keep existing clients, so you don't have to roll out all new configs.
In our case our clients do not yet have a PSK, but if we remove them from the config, wg-easy won't accept it and die.
This patch just changes the config-generation so that missing PSKs will just be ignored. The UI and the generation of new users is not touched, so this only affects configs, where you manually remove the PSK from the wg0.json.
> Import json configurations with no PreShared-Key

- Dockerfile
As this Package `ip` is not maintained anymore (last commit is 2 years ago)
We should remove this Package.
Testing due it break functionality but it shouldn't due our code don't use it.
Refs:
https://github.com/advisories/GHSA-78xj-cgh5-2h22
https://hub.docker.com/layers/library/node/18-alpine/images/sha256-affdf979bd8ec516bf189d451b8ac68dd50adc49adc4c4014963556c11efeda4?context=explore
> Workaround CVE-2023-42282

- src/www/index.html
Aligned detailed stats block to the right on mobile.
There's another option - align everything to the left on mobile. Looks nice to me, what do you think?
<details>
<summary>Right-aligned</summary>
</details>
<details>
<summary>Left-aligned</summary>
</details>
> Fix detailed stats 3

- src/config.js
- src/lib/WireGuard.js
- src/server.js
Lint errors fixed
From @samart45 Tested by @samart45 and @pheiduck
Fixes: https://github.com/wg-easy/wg-easy/issues/795
Fixes: https://github.com/wg-easy/wg-easy/issues/835
Issue duplicate firewall rules if network mode "host" is used:
```
/app # iptables  -v -L -n --line-numbers | grep "51820"
7        0     0 ACCEPT     17   --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:51820
8        0     0 ACCEPT     17   --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:51820
6        5   880 ACCEPT     17   --  *      *       0.0.0.0/0            0.0.0.0/0            udp dpt:51820
/app # iptables -v -L -n --line-numbers | grep "51821"
7       23  1380 ACCEPT     6    --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:51821
```
> feat: graceful shutdown

- README.md
`README.md` was updated to use a one-liner to update WireGuard Easy with Docker Compose.
A note about image tag was added to avoid confusion when one is specified in Compose file and it is other than `latest`, as that would result in no pull and no WireGuard Easy container recreation.
This pull request complements #901.
> Use one command for updating with Docker Compose

- src/config.js
Fixes #943
Closes #140 
Closes #922 
Thank you @utkarsh867
> fix backward compatibility issue

- src/config.js
@pheiduck I realised that we did not check for empty WG_DEFAULT_ADDRESS.
Either it be a required config, or it should be checked if empty.
> fix default WG_DEFAULT_ADDRESS issue

- .dockerignore
- Dockerfile
- package.json
- src/package-lock.json
- src/package.json
- src/server.js
From https://github.com/wg-easy/wg-easy/commit/e153998d296df2b3e17a2fdf38ded888b6e8248f I noticed that both the `nodemon` package installation and file cleanup have been moved to the first stage of the Docker build. Since switching from one stage to another uses a different base and all changes made to the previous one are left behind, I assume that these instructions are no longer needed in the final build and can be completely removed from the `Dockerfile`.
However, the `nodemon` package might come in handy for someone during local development, so I added it back to the project but as a **dev dependency** instead of installing it globally. That is why I also modified the `run` script of `npm` to use `npx` to call the `nodemon` executable from the local modules of the project. Note that …
> Improved local development and Dockerfile

- src/config.js
While ListenPort in file  [WireGuard.js](https://github.com/wg-easy/wg-easy/blob/c6dd456a0703ed1b42ca52d21e8ef52918778377/src/lib/WireGuard.js#L98)  respect WG_PORT environment variable, the iptables rule should respect WG_PORT, not hard code 51820.
> iptables rules may dismatch ListenPort 

- src/lib/Server.js
- src/lib/WireGuard.js
- src/package-lock.json
- src/package.json
- src/www/js/app.js
In reference to #1067, this PR fixes the **directory traversal** (**path traversal**) vulnerability found in the last released version and introduced with bad path handling in the h3 framework's `serveStatic` directive. Now the requested resource paths are handled correctly with the `safePathJoin` function. It takes the base path of the static assets and the path to the requested resource and checks that their union is indeed still a valid **subpath**.
In addition, some minor improvements have been implemented:
- replaced the `uuid` package with the built-in Node `crypto` module. Since its only task was to generate **UUIDv4** for new clients, we can use the `randomUUID` function instead;
- removed the `bcryptjs` package. The only reason it was being used was to implement an authorization …
> Security vulnerability patched and minor improvements

- src/lib/Server.js
While developing an API wrapper, I was so confused while checking for `success `but instead i always got just `succcess`.
Sorry, if this is considered as spam, just close it.
;)
> fix typo in Server.js

- docker-compose.yml
- src/config.js
- src/lib/WireGuard.js
This commit introduces the ability to specify a custom port for the client configuration. This feature is particularly useful when the WireGuard server is behind a port forwarding setup, allowing clients to connect using the correct port number.
With this change, users can now define the desired client port in the configuration file with the env variable ``WG_CONFIG_PORT``, ensuring seamless connectivity even in scenarios where the client's listening port differs from the standard port.
> config: Add support for custom client port configuration

- docker-compose.yml
- src/config.js
- src/lib/WireGuard.js
By @adriy-be
This commit introduces the ability to specify a custom port for the client configuration. This feature is particularly useful when the WireGuard server is behind a port forwarding setup, allowing clients to connect using the correct port number.
With this change, users can now define the desired client port in the configuration file with the env variable WG_CONFIG_PORT, ensuring seamless connectivity even in scenarios where the client's listening port differs from the standard port.
> config: Add support for custom client port configuration 

- README.md
- src/config.js
- src/lib/Server.js
Hey,
This implements `PASSWORD_HASH` and deprecates `PASSWORD` usage, because clear text passwords should not be part of any environment variable (neither in the container nor in the docker environment).  See #1105
Why do we have the tested password sourced from two different places?
1. `req.headers['authorization']`
2. `readBody(event)`
Anyway, I made the password validation DRY and moved it to `isPasswordValid`.
Kind regards
Robert
> feat: introduce PASSWORD_HASH and deprecate PASSWORD

- How_to_generate_an_bcrypt_hash.md
while, as expected:
```console
stevie@fedora:~$ echo '$$'
$$
```
because:
```console
stevie@fedora:~$ echo "$$"
6982
```
and:
```console
stevie@fedora:~$ echo "'$$'"
'6982'
```
The one-liner does not work in bash shell because the docker env version of the hashed password has the process id repeated everywhere there should be a `$$` in the hashed password.
Use the repetition operator in python to avoid any issues backslash escaping might cause across different hosts.
```python
docker_interpolation = hashed.decode().replace('$', '$$');  # Before
docker_interpolation = hashed.decode().replace('$', '$'*2); # After, using repetition operator to avoid $$ in double quotes
```
> Fix bcrypt hash one-liner

- How_to_generate_an_bcrypt_hash.md
- package.json
- src/config.js
- src/package.json
- src/www/css/app.css
- src/www/index.html
Make the `restore`, `backup` and `new` buttons responsive for mobile.
- make buttons responsive on mobile
- update description in [how_to_make_password_hash](https://github.com/wg-easy/wg-easy/blob/master/How_to_generate_an_bcrypt_hash.md) to avoid confusion #1191 
- add new running `scripts` to support `sudo` user
- ~add workspaces to allow running commands like `npm --prefix src run buildcss` or `pnpm run -r buildcss` from the root directory~
- update the `package.json` release field to conform with standards
> fix: responsive buttons on mobile

- .github/workflows/deploy.yml
Hello! I've noticed that the package version format has now changed. The updated version in the [master branch package.json](https://github.com/wg-easy/wg-easy/tree/master/src/package.json) is now like this:
```json
"release": {
"version": "13"
},
```
From before:
```json
"release": "13",
```
Because of this, the Docker build pipeline fails and throws this error:
```
Error: buildx failed with: ERROR: invalid tag "***/wg-easy:{ \"version\": \"13\" }": invalid reference format
```
Fortunately, this issue is easy to solve. I took a look at the line of code in the [deploy.yml](https://github.com/wg-easy/wg-easy/tree/master/.github/workflows/deploy.yml#L36) file and specifically edited line 36. I made a small tweak that fixes the version fetching.
From:
```yml
run: echo RELEASE=$(cat …
```
> Fix "invalid reference format" in production Docker build

- README.md
- docker-compose.dev.yml
- docker-compose.yml
PASSWORD is useless with version 14 so remove the envs for docker, to reduce confusion.
> remove PASSWORD env unused and replace by PASSWORD_HASH

- src/www/index.html
Safari suggests strong password on login page. This PR should fix this problem.
> Add autocomplete attribute to password input

- How_to_generate_an_bcrypt_hash.md
- docker-compose.yml
Hello! I noticed repeated changes to docker-compose.yml in previous commits. When applying the single-quote pattern, I encountered the following warning:
`WARN[0000] The "hBCoykrB95WSzuV4fafBzOHWKu9sbyVa34GJr8VV5R" variable is not set. Defaulting to a blank string.`
Additionally, the `PASSWORD_HASH` variable value was incorrect when viewed inside the container.
Remove the single quotes and insert an extra `$` before each existing `$`. After this modification, the program works as expected.
There might be inconsistencies in Docker Compose versions between us, leading to different behavior in handling escape characters.
My environment information:
```bash
docker --version
Docker version 27.1.1, build 6312585
docker compose version
Docker Compose version v2.29.1
```
The changes in this PR …
> fix(Doc): fix escaping issue for PASSWORD_HASH in docker-compose.yml

- README.md
- docker-compose.yml
- src/config.js
- src/lib/Server.js
- src/lib/WireGuard.js
- src/package-lock.json
- src/package.json
- src/www/index.html
- src/www/js/api.js
- src/www/js/app.js
Supports displaying short links for easy downloading on TVs and Android TVs
This setting shows a short link on the page to download the config file
This is to make it convenient for Android TVs to type in a short address and download the config file
I tested this on my server, and on my laptop. By adding the UI_SHOW_LINKS parameter to the docker-compose.dev.yml file with different values I looked at the result of the page after restarting the container
> Supports displaying short links

- How_to_generate_an_bcrypt_hash.md
- src/wgpw.mjs
The changes are contained in `src/wgpw.mjs`. The password parameter is now also optional.
If the user does not provide any arguments, the tool will default to generating a hash and  prompt the user for a password through `stdin`.
The password is not echoed back, just like any other command-line log-in prompt (ie. sudo).
This is done to avoid having the password written to the user's shell history in plain text. Just a security consideration.
These changes only affect `wgpw`.
It has been tested by building the docker image in Fedora using Podman.
All combinations of arguments have been tested. It still generates a hash when given a password through the arguments list. It still validates a hash if given as a second argument, comparing it to the first argument.
> Allow wgpw to prompt for a password through stdin

- src/server/api/account/create.post.ts
- src/server/api/account/setup.post.ts
- src/server/api/cnf/[oneTimeLink].ts
- src/server/api/features.get.ts
- src/server/api/lang.get.ts
- src/server/api/session.post.ts
- src/server/api/wireguard/client/[clientId]/generateOneTimeLink.post.ts
- src/server/middleware/session.ts
- src/server/middleware/setup.ts
- src/server/utils/WireGuard.ts
- src/server/utils/config.ts
- src/server/utils/session.ts
- src/services/database/lowdb.ts
- src/services/database/migrations/1.ts
- src/services/database/repositories/client.ts
- src/services/database/repositories/database.ts
- src/services/database/repositories/system.ts
- src/services/database/repositories/user.ts
Improves the Repository Pattern to be more intuitive and developer friendly
Previously you had to add a new function to the interface, database provider and database implementation
Also the naming had to be unique and e.g. always append what "table" you are referring to
Now you have to add the function to the Provider for that "table" and implement it in the implementation for that "table"
`Database.updateClient` -> `Database.client.update`. This makes it easier to find the right function and what the line of code does
Locally
N/A
> Feat: Improve Repository pattern

- src/server/middleware/session.ts
- src/server/utils/Database.ts
- src/server/utils/WireGuard.ts
- src/server/utils/session.ts
- src/services/database/lowdb.ts
- src/services/database/repositories/database.ts
This improves Database handling and DX.
Instead of praying that `#db` is set. This throws a Error message such that the frontend shows a 500 page and users know that the "Database [is] not yet initialized".
And if in the backend a function didn't wait properly for the Database (and action is not made from user) it will crash the server.
This should avoid any undefined state where e.g. migrations are not done.
The WireGuard Interface is now started after DB is connected instead of having to poll the connection state
Fix weird issues
Locally
N/A
> Feat: Improve Database Handling

- How_to_generate_an_bcrypt_hash.md
- docker-compose.yml
Update for How_to_generate_an_bcrypt_hash.md:
- Inclusion of single quotes for password with docker run command
- Addition of "--rm" parameter to docker run command, to cleanup the (new) wg-easy container which gets created automatically during with the password hash generation command
Update for docker-compose.yml:
- Addition of missing # before the comment on PASSWORD_HASH line
Small documentation updates related to #1433 and #1469 
N/A (Documentation updates)
> Document updates: docker-compose.yml / How_to_generate_an_bcrypt_hash.md

- Dockerfile
It's breaking nightly builds
latest npm is breaking nightly builds
fixes iptables paths as well.
It's solves nightly builds.
via CI.
> Dockerfile: don't update npm to latest fix iptables paths

- .gitignore
- src/.gitignore
- src/drizzle.config.ts
- src/server/api/admin/hooks.get.ts
- src/server/api/admin/hooks.post.ts
- src/server/api/admin/interface/cidr.post.ts
- src/server/api/admin/interface/index.get.ts
- src/server/api/admin/interface/index.post.ts
- src/server/api/admin/userconfig.get.ts
- src/server/api/admin/userconfig.post.ts
- src/server/api/setup/5.post.ts
- src/server/database/repositories/hooks/service.ts
- src/server/database/repositories/interface/schema.ts
- src/server/database/repositories/interface/service.ts
- src/server/database/repositories/userConfig/service.ts
- src/server/database/sqlite.ts
- src/server/routes/metrics/prometheus.get.ts
- src/server/utils/WireGuard.ts
This streamlines multi interface support.
The only reference to the default `wg0` interface is in the database layer.
renamed database to `wg-easy.db` as its not only about the `wg0` interface anymore
Currently the reference the wg0 was all over the place, as I started adding multi interface support but I don't think it makes sense. wg-easy is shifting towards the user. So the admin can just hand out accounts and the user can do everything themselves.
But now the user would download a client and wonder why it can't properly communicate with the other client (as its on another interface) or the user has to choose which interface to create/download a client from. but why would he know what that even means.
> Chore: Remove multi interface support

- Dockerfile
- Dockerfile.dev
HEALTHCHECK options should always come before the CMD instruction
Now HEALTHCHECK options passed to CMD:
`docker inspect wgeasy`
```
"Healthcheck": {
"Test": [
"CMD-SHELL",
"/usr/bin/timeout 5s /bin/sh -c \"/usr/bin/wg show | /bin/grep -q interface || exit 1\" --interval=1m --timeout=5s --retries=3"
]
},
```
docs:
https://docs.docker.com/reference/dockerfile/#healthcheck
> fixed Dockerfile HEALTHCHECK syntax

- src/server/utils/handler.ts
It should only require the auth header and the bearer token if the password is set
in the current implementation it would require the header but not validate it
> Fix: only require metrics password if set

- README.md
- docs/content/examples/tutorials/auto-updates.md
- docs/content/examples/tutorials/docker-run.md
- src/app/components/Form/NullArrayField.vue
- src/app/components/Ui/Footer.vue
- src/app/pages/admin/config.vue
- src/app/pages/clients/[id].vue
- src/i18n/locales/en.json
- src/server/database/migrations/0000_short_skin.sql
- src/server/database/migrations/meta/0000_snapshot.json
- src/server/database/migrations/meta/0001_snapshot.json
- src/server/database/migrations/meta/_journal.json
- src/server/database/repositories/client/schema.ts
- src/server/database/repositories/client/service.ts
- src/server/database/repositories/client/types.ts
- src/server/utils/wgHelper.ts
This PR implements a Global config override.
Instead of copying the default config on client creation. leave it null. but give the user the option to edit it per client
This makes it possible to easily change the DNS for all clients (by changing the global config) and only having to change the overrides
> Feat: Global config override

- CHANGELOG.md
- docs/content/examples/tutorials/podman.md
- src/server/utils/config.ts
- src/server/utils/template.ts
This adds the UI port to the hooks template
The recommended nftables rules are more strict and therefore need the ability to allow the ui port
Closes https://github.com/wg-easy/wg-easy/pull/1734 to allow creating a `:development` tag
> Fix: Add ui port to template

- src/server/utils/WireGuard.ts
This PR fixes #1786 
Not a sync does not happen every minute but only if a save is actually needed. in this case if a client is expired.
> Fix: sync / rekey issue

- docs/content/advanced/migrate/from-14-to-15.md
- docs/content/examples/tutorials/basic-installation.md
- docs/content/examples/tutorials/caddy.md
- docs/content/examples/tutorials/traefik.md
Replaced `docker-compose` with `docker compose` for compatibility with Compose V2
Replaced usage of `docker-compose` CLI with `docker compose`, which is now the officially recommended and supported method starting from Docker Compose V2. This change affects all places where `docker-compose` was used in scripts, documentation, or instructions.
This change ensures compatibility with modern Docker setups, where `docker-compose` (the standalone Python binary) is deprecated and no longer pre-installed. Using `docker compose` (integrated plugin) avoids dependency issues and aligns with current Docker best practices. Using the command may cause a `docker-compose: command not found` error when using newer versions.
Manually tested `docker compose up -d` in a local development environment running …
> Updated container launch commands

- docs/content/examples/tutorials/traefik.md
Updated the wg-easy docker compose file when using traefik. Added the "traefik.docker.network" label, this fixes a bug where the dashboard was not available because 2 network are assigned to the wg-easy docker compose file.
Without defining what network traefik has to use, it chooses one randomly which may result in the dashboard not being available.
From traefik documentation: "If a container is linked to several networks, be sure to set the proper network name, otherwise it will randomly pick one." [traefic docs](https://doc.traefik.io/traefik/reference/routing-configuration/other-providers/docker/#traefikdockernetwork)
I am running my wg-easy on my own home lab and ran into this issue myself.  Multiple services had the same problem that disappeared when adding the docker network label.
> Updated traefik documentation

- docs/content/examples/tutorials/adguard.md
This pull request adds a new, comprehensive tutorial for integrating AdGuard Home with an existing `wg-easy` and Traefik setup.
**Key Features:**
*   Follows the project's multi-compose-file structure for consistency.
*   Provides step-by-step instructions for adding AdGuard Home for network-wide DNS ad-blocking.
*   Uses `wg-easy`'s unattended setup feature for a robust and reproducible configuration.
This guide provides a clear path for users to add DNS filtering to their existing VPN setup.
> docs: Add AdGuard Home tutorial
